import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import ConditionalMenu from "@/components/ConditionalMenu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "SolvIt DBS",
  // Digital Business System
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 



{
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-0 overflow-x-auto bg-[#9FBFC5] whitespace-nowrap flex`}
      >
        
        <div className="flex-1">
          <ConditionalMenu/>
          
          {children}
        </div>
      </body>
    </html>
  );
}


