import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


import ConditionalMenu from "@/components/ConditionalMenu";
import { ThemeProvider } from "@/components/theme-provider";
import Head from "next/head";
import RegisterSW from "@/components/RegisterSW";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "SC- DBS",
  // Digital Business System
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 



{
  
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#0f4f20" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <link rel="apple-touch-icon" href="icons/icon-192x192.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-0 overflow-x-auto bg-[#9FBFC5] whitespace-nowrap flex`}
      >
        <RegisterSW />
        <div className="flex-1">
          
          
           <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            
            <ConditionalMenu/>
            {children}
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}


